#!/usr/bin/env python3
"""Exact reported values; no digitized or illustrative numerical results."""
import json
from pathlib import Path
OUT=Path(__file__).resolve().parent
URL='https://arxiv.org/html/2506.10943v2'
rows=[('base','Base model',[32.7,32.7,29.0]),('passage','Passage only',[33.5,36.0,31.2]),('synthetic','Self-generated data',[39.7,50.6,43.4]),('gpt41','GPT-4.1 data',[46.3,59.4,49.2]),('seal','SEAL',[47.0,58.2,46.4])]
settings=[('single','Single passage (LoRA)','1 passage; LoRA'),('cpt200','Continued pretraining: 200 passages','200 passages; full finetuning'),('cpt2067','Continued pretraining: 2067 passages','2067 passages; full finetuning')]
arc=[('icl','ICL',0),('selfedit','Self-edit, no RL',20),('seal','SEAL',72.5),('oracle','Oracle TTT',100)]
sources=[{'id':'knowledge','kind':'paper','locator':URL,'location':'Table 2, all five rows and all three columns; Section 4.2 and Appendix B for protocol'}, {'id':'arc','kind':'paper','locator':URL,'location':'Table 1, all four rows; Section 4.1 and Appendix A for filtered-task protocol'}, {'id':'method','kind':'paper','locator':URL,'location':'Sections 3.1–3.2, Algorithm 1 and Figures 1–3'}, {'id':'author_site','kind':'artifact','locator':'https://jyopari.github.io/posts/seal','location':'Method overview and domain-instantiation figures; viewed as original pixels, numerical website text not used'}]
metrics=[{'id':s[0],'label':'No-context SQuAD accuracy: '+s[1],'unit':'percent','direction':'higher'} for s in settings]+[{'id':'arc','label':'Successful adaptations on filtered ARC tasks','unit':'percent','direction':'higher'}]
results=[]
for method,label,values in rows:
 for (sid,setting,budget),value in zip(settings,values):
  results.append({'id':method+'_'+sid,'method_id':method,'metric_id':sid,'value':value,'source_id':'knowledge','source_location':'Table 2: '+label+' row, '+setting+' column','comparison':{'dataset':'SQuAD; Qwen2.5-7B','split':'Table 2 evaluation questions, no passage in context','budget':budget+'; method-specific tuned hyperparameters, not compute matched','protocol':'Section 4.2; reported Table 2 comparison'}})
for method,label,value in arc:
 results.append({'id':method+'_arc','method_id':method,'metric_id':'arc','value':value,'source_id':'arc','source_location':'Table 1: '+label+' row','comparison':{'dataset':'ARC curated subset; Llama-3.2-1B-Instruct','split':'8 filtered evaluation tasks (11 training tasks)','budget':'5 independently applied self-edits per evaluation task for SEAL and self-edit baseline; method-dependent adaptation','protocol':'Section 4.1 and Table 1; percentage of edits yielding correct outputs for self-editing methods'}})
claims=[{'id':'single_vs_own','type':'percentage_point_difference','baseline_result_id':'synthetic_single','proposed_result_id':'seal_single','display_value':7.3,'decimals':1}]
charts=[]
for sid,_,_ in settings:
 charts.append({'type':'dot','metric_id':sid,'series':[{'label':l,'values':[vs[[x[0] for x in settings].index(sid)]],'result_ids':[m+'_'+sid]} for m,l,vs in rows]})
charts.append({'type':'bar','metric_id':'arc','series':[{'label':l,'values':[v],'result_ids':[m+'_arc']} for m,l,v in arc]})
base={'version':1,'status':'draft','provenance':{'data_status':'reported','sources':sources,'retrieved_utc':'2026-09-12','paper_version':'2506.10943v2 (18 September 2025)','extraction':'Exact HTML table values, checked against source rows. Project-page CPT prose is stale relative to v2 and excluded.','uncertainty':'No entry-specific uncertainty in Tables 1–2; no error bars or significance claim.','example_status':'Invented Lyra passage and grid examples illustrate representations; not reported model outputs.'}}
spec={**base,'kind':'teaser','figure':{'width_in':7,'height_in':4.8,'concept_fraction':0.34,'title':'SEAL: learn how to write your own training data','geometry_source':'build_figures.py','note':'Original redesign, reported data; schematic example. Two-column draft, venue unspecified.'},'evidence':{'metrics':metrics,'results':results,'claims':claims},'charts':charts,'row_order':[r[0] for r in rows],'settings':settings,'method_labels':{m:l for m,l,v in rows},'arc_order':[r[0] for r in arc],'arc_labels':{m:l for m,l,v in arc}}
method={**base,'kind':'method','figure':{'width_in':7,'height_in':5.35,'title':'SEAL trains an editor through the results of adaptation','geometry_source':'build_figures.py'},'evidence':{'metrics':[],'results':[],'claims':[]},'method_contract':{'input':'Context C plus downstream evaluation task tau during RL training','policy':'Current LM with parameters theta_t samples candidate self-edits','inner':'Each candidate independently adapts a copy of the current weights by SFT (LoRA in the demonstrated individual updates)','evaluation':'Downstream task performance determines reward; no gradient through reward','outer':'On-policy ReST-EM: select rewarded context/edit pairs, SFT edit generation to obtain theta_(t+1)','selection':'Generic positive-improvement reward; knowledge-incorporation implementation selects the best candidate','deployment':'Generate self-edit and adapt; outer reward-training loop is not required at inference','knowledge':'Generated implications are finetuning data; downstream QA omits the source passage','fewshot':'Self-edit selects augmentations and training settings; adapted model predicts held-out output'},'canonical_geometry':'build_figures.py:method_figure'}
for name,obj in [('teaser.spec.json',spec),('method.spec.json',method),('reported-tables.json',{'source':URL,'table2':rows,'table1':arc})]: (OUT/name).write_text(json.dumps(obj,indent=2)+'\n')
